app:
  host: ${HOST_NAME}
  port: ${HOST_PORT}
  name: "MeetUps Guru"
connections:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PORT}
    database:
      master:
        name: "postgres"
        host: ${MASTER_DB_HOST}
        port: ${MASTER_DB_PORT}
        password: ${MASTER_DB_PASSOWRD} 
