[package]
name = "scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
edgedb-derive = "0.5.2"
edgedb-protocol = "0.6.1"
edgedb-tokio = "0.5.1"
tokio = "1.40.0"
